### ISSUE TITLE
Error after 2 epochs

### ISSUE THREAD

**Issue by sherwanimoizkhan** [Blade6570/Learningimage-to-imagetranslationusingpairedandunpairedtrainingsamples#6]
model [CycleGANModel] was created
Setting up a new session...
create web directory ./checkpoints/mygan_70/web...
End of epoch 1 / 200 	 Time Taken: 24 sec
learning rate = 0.0002000
(epoch: 2, iters: 37, time: 0.579) D_A: 0.282 G_A: 0.268 Cyc_A: 0.662 D_B: 0.284 G_B: 0.402 Cyc_B: 0.700 idt_A: 0.391 idt_B: 0.440 
Traceback (most recent call last):
  File "train.py", line 50, in <module>
    visualizer.plot_current_errors(epoch, float(epoch_iter)/dataset_size, opt, errors)
  File "/media/rusica/0E3E135A0E3E135A/MoizBackup/cycgan/pairunpair/Learningimage-to-imagetranslationusingpairedandunpairedtrainingsamples/util/visualizer.py", line 113, in plot_current_errors
    win=self.display_id)
  File "/home/rusica/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 389, in wrapped_f
    return f(*args, **kwargs)
  File "/home/rusica/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 1715, in line
    update=update, name=name)
  File "/home/rusica/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 389, in wrapped_f
    return f(*args, **kwargs)
  File "/home/rusica/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 1640, in scatter
    return self._send(data_to_send, endpoint=endpoint)
  File "/home/rusica/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/home/rusica/anaconda3/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/rusica/anaconda3/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/rusica/anaconda3/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/rusica/anaconda3/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable

Kindly help me out!

**Comment by Blade6570** [comment]
Hi, I am unable to replicate this issue in my env. However, I have added a fix depending on the error message so please check and let me know. If the issue persists then let me know the versions of visdom, dominate, PyTorch and Python.
